[project]
name = "books-medallion"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "black>=25.11.0",
    "notebook>=7.4.7",
    "pyspark>=4.0.1",
    "ruff>=0.14.5",
    "structlog>=25.5.0",
]
